# Generated by Django 6.0.4 on 2026-04-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="distance_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_plan",
            field=models.TextField(blank=True, null=True),
        ),
    ]
