# Generated by Django 6.0.4 on 2026-04-27 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trip_distance_km_trip_trip_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="trip",
            name="total_days",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
