# Generated by Django 6.0.4 on 2026-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_trip_created_at_trip_total_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="current_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="current_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="dropoff_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="dropoff_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="pickup_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="pickup_lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
